---
title: "RAC Hoop Glossary"
---

<br>

#### *This page describes terms frequently used during RAC hoops*

Terms are grouped by category and listed alphabetically in those categories. Terms in *italics* have been identified and defined. Terms that are not *italicized* are part of the lexicon, but require definitions. 


**To submit a term and definition or a definition for an existing term, use [this link](https://github.com/jacobtnyoung/RHG/issues)**


<br>

****

##### Terms/Phrases Pertaining to Wins/Loses  

*Championship*-A game played to 31 to decide which of the opposing teams will have the winning record for the day. A game to 31 is worth 1.5 games.  

*Defeated*-When a player or players loses every game they play on a specific day of hoop.  

*Fellowship* (other usage is the term *Sweep*)-When a single team wins every game played on a specific day of hoop. Strictly requires winning of all games played that day and by original team members.  

Pro bowl-  

Super true championship-  

True championship-  

*True fellowship*-When the first game winning 4 players sweep the day including the championship with no subs.  

*Undefeated*-When a player wins every game they play on a specific day of hoop. Note, a player can go "undefeated" and you earn "Fellowship" if they do not participate in the first game played on a given day.  


**To submit a term and definition or a definition for an existing term, use [this link](https://github.com/jacobtnyoung/RHG/issues)**

<br>

****

#### Terms/Phrases Pertaining to "Checks"  

Courtesy-  

*Illegitimate*-A game stoppage used by the defense. The check is so called "illegitimate" when it is used purely to slow down the offense and set your defense.  

*Score*-A game stoppage used to take stock of the score.  

Welfare-  


**To submit a term and definition or a definition for an existing term, use [this link](https://github.com/jacobtnyoung/RHG/issues)**

<br>

****

#### Misc Terms/Phrases
*Air decision*-Occurs when a player passes and the decision for the target of the pass is made while in the air. See also the sarcastic usage of "good pass".

*As deep as []'s wife*-Use to indicate a shot taken at considerable distance from the hoop. The specific name mentioned between the brackets is player specific.

Ave (also Ave-ing in)-

*Bank*-A generic term to indicate the use of the backboard to complete a shot. See Protractor for disambiguation.

*Beeped*-When a player, during a shot attempt, experiences a verbalized "beep" from another player. Some players, under particular circumstances, will execute a "self-beep".


*Block party*-The occurrence of multiple blocks by one or multiple defenders on one or multiple opponents.

Brandonoma-

*Can't teach strong/big*-When an offensive player, despite the presence of good defense, prevails in a layup or closely contested shot near the rim and the reason for their making the strong is attributed to their strength or size. A close variation is: can't teach fast, as well as other derivative usages: can't teach ______ .

Carnie shot-

*Clearly egregious*-Used to indicate a traveling violation that deserves added commentary given the egregiousness of the violation.

*Creeper*-A shot that does not directly go in immediately, but instead, creates a moment of uncertainty, yet eventually goes through the hoop.

Curable, but serious at its peak-

Curable, we think-

*Dick is in*-Indication by another hooper that Dick will be playing. Other usages vary widely but include (though not an exhaustive list): I got Dick, Who has Dick?, Hey [insert player name], you take Dick, etc.

*Disqualified*-The person shooting in for the next game misses everything.

*Double-tap*-When a player knocks the ball out of bounds and immediately before it goes out a player on the opposing team touches the ball.

*DQ, Dairy Queen Blizzard*-When one is shooting in between games and misses everything including the rim, net, backboard, and the chance of playing again.

*Excuse me, sir and/or ummm, sir*-Used when a player on the same team takes, at a minimum, 2 consecutive ill-advised shots on 2 consecutive possessions, resulting in zero points (and likely fast break points for the other team due to the long rebound).

*Full FDR*-When a player requires a knee brace for each knee.

*Half FDR*-When a player requires a single knee brace.

*Good pass*-A term, used sarcastically, to mock the judgement of a particular player after a poor pass.

Ill-advised-

*In w #s*-A common, yet unnecessary, acknowledgment from one submitting their name to hoop as no one would be able to play without said #s.

Index game-

*Is it?*-An opposing player questioning the execution of a shot or pass, only to be dismayed.

*Jump?*-1) when the ball is tied up between two players (preferably on opposite teams), 2) when a play occurs and the outcome is not immediately apparent and the ball is awarded to the team with the possession arrow, 3) when a straightforward call is questioned in the name of psych-ops.

*Just the tip*-A contested pass that only touches the tip of the defenders finger.

*Justice*-When a debated call results in a change of possession and in the subsequent position play ensues that nullifies the prior debated call.

*Layups?*-After several attempts to shoot-in for a game do not yield a clear outcome, this term is used jokingly so as to suggest speeding up the decision.

Look out, Gerald-

Mayvian flu-

MeAndy-

*Move it back*-After several attempts to shoot-in for a game do not yield a clear outcome, the players move the shoot-in shot from the 3-point line to the free-throw line of the opposing side. Can also be used to trick unsuspecting players by particular individuals.

*Newly found illness*-

*Niner-Niner*-Used to indicate a score of 9-9 or 19-19. See Sixty-Nine for more particular usage.

*Noon start*-An archaic term used in a bygone era to coordinate a 12:00 pm start.

Not enough recent testing to know-

*No 3's*-An encouragement to the other team to shoot a 3 when they need 2 to win, or, alternatively, an admonishment to the defensive team from another defensive team member that seems to almost never work.

*Number 9*-Either the last person in the door who misses playing in the first game or, alternatively, anyone who walks in the door whom other players want to make feel bad whether they're actually the ninth player.

*Out-the-door shot*-When a player tries to get in some extra bicep curls before the game is officially over.

*Protractor*-A term used to signal the use of an precisely calculated angle when attempting a shot. Note the difference from bank which is a generic term to indicate the use of the backboard. Protractor is more specifically used to indicate the angle of the shooter's position.

*Psych-ops*-A call or move with no rational purpose other than to get one’s opponent to question the call.

*Rule TA.1*-A rule governing assignment of incoming players to a team that lost players or a new team. A shape-shifting concept incapable of being documented that depends entirely on the vigor of the advocate and his need for a roster upgrade.

*Rick*-When a player attempts a shot that hits the portion of the backboard that is vertical and perpendicular to the court.

Samsonite-

*SHORT!*-A shot that only touches the tip of the rim.

*Sixty-nine*-Remarked when the score is 6-9, 16-9, 6-19, or 16-19. Also, frequently mentioned subsequent to: Okay, it is 3-6, let's get a 3 here. Further, a 3 pointer made after announcing Sixty-nine is followed by the term Niner-Niner if the team that was down evens the score.

*“Sparingly”*-Apparently means at least once or twice a game in every game.

Sticky D-

*Sub?/You ok?*-A question put forth to inquire as to whether a player needs to be replaced. Used seriously and rhetorically in various instances.

*Taps*-Played to indicate that the outcome of a game is seemingly inevitable given the disparity in the score.

*Tomahawk*-When a defensive player attempts to block a shot and egregiously chops at the offensive player.

*Turnover*-Legal fiction.

*Who's got (insert players name)?*-Used to reference poor D on an opposing player who continues to score...over...and over...and over.


To submit a term and definition or a definition for an existing term, use [this link](). 